name: csd1
channels:
    - conda-forge

dependencies:
   - python=3.9
   - pip
   - git
   - compas>=1.17.1
   - compas_cgal>=0.5.0
   - compas_occ>=0.7.0
   - compas_view2>=0.9.0
   - python-planarity
   - pip:
     - black
     - qt-material
     - compas_cloud
     - compas_ui
     - compas_ags
     - compas_igs2
